# Generated by Django 4.2.7 on 2023-12-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Green', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrades',
            name='profile_image',
            field=models.URLField(default='https://ww.gffjd.com'),
        ),
        migrations.AddField(
            model_name='mytrades',
            name='profit_share',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='mytrades',
            name='win_rate',
            field=models.DecimalField(decimal_places=2, default=23.22, max_digits=999),
            preserve_default=False,
        ),
    ]
