# Generated by Django 4.2.7 on 2023-12-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Green', '0002_mytrades_profile_image_mytrades_profit_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytrader',
            name='asset_under_management',
            field=models.DecimalField(decimal_places=2, default=23872648.23, max_digits=999),
            preserve_default=False,
        ),
    ]
