# Generated by Django 4.2.7 on 2023-12-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Green', '0004_copytrader_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=999)),
                ('mine_rate', models.DecimalField(decimal_places=2, max_digits=999)),
                ('image', models.URLField(default='https://ww.gffjd.com')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
