# Generated by Django 4.2.7 on 2023-12-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Green', '0005_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('form', models.CharField(choices=[('CRYPTO', 'CRYPTO'), ('STOCKS', 'STOCKS'), ('CURENCIES', 'CURENCIES'), ('INDICES', 'INDICES')], max_length=200)),
                ('image', models.URLField(default='https://ww.gffjd.com')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AlterField(
            model_name='coin',
            name='value',
            field=models.DecimalField(decimal_places=6, max_digits=999),
        ),
    ]
