# Generated by Django 4.2.7 on 2023-12-30 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Green', '0006_market_alter_coin_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='form',
            field=models.CharField(choices=[('CRYPTO', 'CRYPTO'), ('STOCKS', 'STOCKS'), ('CURRENCIES', 'CURRENCIES'), ('INDICES', 'INDICES')], max_length=200),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('form', models.CharField(choices=[('CRYPTO', 'CRYPTO'), ('STOCKS', 'STOCKS'), ('CURRENCIES', 'CURRENCIES'), ('INDICES', 'INDICES')], max_length=200)),
                ('value', models.DecimalField(decimal_places=6, max_digits=999)),
                ('image', models.URLField(default='https://ww.gffjd.com')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
