# Generated by Django 4.2.7 on 2023-12-31 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Green', '0008_remove_wishlist_value_market_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyTrades',
            new_name='CopiedTrade',
        ),
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='WatchList',
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('GBP', 'GBP')], max_length=50)),
                ('email', models.EmailField(blank=True, default='test@gmail.com', max_length=254, null=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(help_text='describe your location', max_length=70)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
