# Generated by Django 4.2.7 on 2023-12-31 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Green', '0011_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='pay_in',
            field=models.CharField(choices=[('BITCOIN', 'BITCOIN'), ('ETHEREUM', 'ETHEREUM')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='ammount',
            field=models.DecimalField(decimal_places=2, max_digits=999, validators=[django.core.validators.MinValueValidator(500.0)]),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='fund',
            field=models.CharField(choices=[('TRADING BALANCE', 'TRADING BALANCE'), ('BITCOIN MINIG', 'BITCOIN MINIG'), ('DOGECOIN MINING', 'DOGECOIN MINING'), ('ETHEREUM MINING', 'ETHEREUM MINING'), ('BINANCE COIN MINING', 'BINANCE COIN MINING'), ('COSMO (ATOM) MINING', 'COSMO (ATOM) MINING')], default=1, max_length=100),
        ),
    ]
