# Generated by Django 4.2.7 on 2023-12-31 16:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Green', '0012_deposit_pay_in_alter_deposit_ammount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=999, validators=[django.core.validators.MinValueValidator(500.0)])),
                ('fromacc', models.CharField(choices=[('TRADING BALANCE', 'TRADING BALANCE'), ('BITCOIN MINIG', 'BITCOIN MINIG'), ('DOGECOIN MINING', 'DOGECOIN MINING'), ('ETHEREUM MINING', 'ETHEREUM MINING'), ('BINANCE COIN MINING', 'BINANCE COIN MINING'), ('COSMO (ATOM) MINING', 'COSMO (ATOM) MINING')], default=1, max_length=100)),
                ('wallet', models.CharField(choices=[('BITCOIN', 'BITCOIN'), ('ETHEREUM', 'ETHEREUM')], default=1, max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
