# Generated by Django 4.2.7 on 2024-01-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Green', '0019_watchlist_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='copiedtrade',
            name='profile_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='copytrader',
            name='profile_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='market',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
