# Generated by Django 4.2.7 on 2024-01-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Green', '0020_alter_coin_image_alter_copiedtrade_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositcoin',
            name='qrcode',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
