# Generated by Django 4.2.7 on 2024-01-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Green', '0022_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='openclosedtrade',
            name='loss_or_gain',
            field=models.CharField(choices=[('LOSS TRADE', 'LOSS TRADE'), ('GAIN TRADE', 'GAIN TRADE')], default=1, max_length=500),
        ),
    ]
