# Generated by Django 4.2.11 on 2024-06-19 04:35

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('Green', '0024_alter_coin_image_alter_copiedtrade_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='image',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
    ]
