# Generated by Django 4.2.11 on 2024-06-19 05:28

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('Green', '0025_alter_market_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='image',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
    ]
