# Generated by Django 4.2.7 on 2023-12-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Green', '0003_copytrader_asset_under_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytrader',
            name='days',
            field=models.PositiveIntegerField(default=234),
            preserve_default=False,
        ),
    ]
