# Generated by Django 4.2.7 on 2024-01-13 11:43

import Green.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Green', '0015_openclosedtrade_trade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='account_name',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='account_number',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='bank_name',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='cashapp',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='paypal',
            field=models.EmailField(blank=True, default='none@ultragreen.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateField(validators=[Green.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='wallet',
            field=models.CharField(blank=True, choices=[('BITCOIN', 'BITCOIN'), ('ETHEREUM', 'ETHEREUM')], default=1, max_length=200, null=True),
        ),
    ]
