# Generated by Django 4.2.7 on 2024-01-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Green', '0018_depositcoin_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='value',
            field=models.DecimalField(decimal_places=6, default=384.3, max_digits=999),
            preserve_default=False,
        ),
    ]
